version: '3.8'

services:
  founderlink-postgres:
    image: postgres:15-alpine
    container_name: founderlink-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dheeraj
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: startups_db 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  founderlink-mongo:
    image: mongo:6.0
    container_name: founderlink-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  founderlink-rabbitmq:
    image: rabbitmq:3-management-alpine # Includes the web UI dashboard
    container_name: founderlink-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # The port your microservices use to send messages
      - "15672:15672" # The web UI port (http://localhost:15672)

  founderlink-zipkin:
    image: openzipkin/zipkin
    container_name: founderlink-zipkin
    restart: always
    ports:
      - "9411:9411"

volumes:
  postgres_data:
  mongo_data:
